spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017}
      database: ${MONGO_DATABASE:floripa}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306/ibiza?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true

application:
  title: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'

scheduled-times:
  start-process: 0/05 0/1 * 1/1 * ?

integrations:
  ml-api-register:
    url: ${ML_API_REGISTER}
    name: ml-register